# Generated by Django 4.0.6 on 2022-08-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followerscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='btm-baner-avatar.png', height_field=300, upload_to='profie_images', width_field=300),
        ),
    ]
