# Generated by Django 4.0.6 on 2022-08-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='btm-baner-avatar.png', upload_to='profie_images'),
        ),
    ]
